spring:
  sql:
    init:
      mode: always
  application:
    name: PRI
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:/db/migration
    schemas: employees
    baselineOnMigrate: true
    enabled: true
  datasource:
    url: jdbc:postgresql://172.17.0.1:5432/java_db?currentSchema=test25
    username: api
    password: api
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariPool
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql=true:
        default_schema: test25
    defer-datasource-initialization: true
  ldap:
    urls: ldaps://dc2-2016.labs.wmi.amu.edu.pl:636/
    base: dc=labs,dc=wmi,dc=amu,dc=edu,dc=pl
logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: INFO
server:
  port: 8082

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs
thesis-module:
  generate-theses-and-chapters-on-startup: true

security:
  jwt:
    enabled: true
    secret: 1wqzxgYaZhpyEfRZIRdwSNN4RCpfBwjfpSSpOhc46Ts
    header: Authorization
    prefix: "Bearer "

# LDAP properties (domain kept for reference)
pri:
  ldap:
    domain: labs.wmi.amu.edu.pl
    enabled: false
  # JWT properties compatible with main module (not sure if needed...)
  app:
    jwtCookieName: accessToken
    jwtSecret: 1wqzxgYaZhpyEfRZIRdwSNN4RCpfBwjfpSSpOhc46Ts
    jwtExpirationMs: 86400000
baseUrlToFile: http://150.254.78.134:${server.port}/api/v1/download/
