version: '3.8'
services:
  prib:
    image: ghcr.io/jarrobots/pri_backend:latest
    container_name: prib
    ports:
      - "${PRIB_PORT:-8082}:8082"
    networks:
      - pri-network
    env_file:
      - config.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./ldap-truststore.jks:/opt/ldap-truststore.jks:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8082/actuator/health | grep UP || exit 1" ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 60s

  prif:
    image: ghcr.io/b0bpri/pri_front:latest
    container_name: prif
    ports:
      - "${PRIF_PORT:-3000}:3000"
    networks:
      - pri-network
    env_file:
      - config.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000/ | grep 'PRI' || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 60s

watchtower:
  image: containrrr/watchtower:latest
  container_name: watchtower
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  env_file:
    - config.env
  environment:
    - DOCKER_API_VERSION=1.44
    - WATCHTOWER_CLEANUP=true           
  restart: always
  command: --schedule "0 4 * * *" prib prif

networks:
  pri-network:
    driver: bridge
    name: pri-network
